networks:
  proxylampy:
    external: true
services:
  www:
    image: node:22.12.0
    working_dir: /app
    command: >
      sh -c "npm install && npm run start"
    volumes:
      - ${PWD}/apps:/app:delegated
    networks:
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.react.rule=Host(`react.traefik.me`)"
        - "traefik.http.routers.react-tls.tls.domains[0].main=react.traefik.me"
        - "traefik.http.routers.react.tls=true"
        - "traefik.http.services.react.loadbalancer.server.port=3000"
