version: 3

# Taskfile principal - Tâches globales et inclusions
# Charge automatiquement les variables depuis le fichier .env s'il existe
dotenv: [ '.env' ]

includes:
  docker: ./taskfiles/docker/Taskfile.yml
  utils: ./taskfiles/utils/Taskfile.yml
  env: ./taskfiles/env/Taskfile.yml
  nodejs: ./taskfiles/nodejs/Taskfile.yml
  download: ./taskfiles/download/Taskfile.yml

vars:
  # Variables avec valeurs par défaut depuis .env ou valeurs de fallback
  PROJECT_NAME: '{{.PROJECT_NAME | default "react"}}'
  ENVIRONMENT: '{{.ENVIRONMENT | default "development"}}'
  STACK_NAME: '{{.STACK | default "react"}}'
  FOLDERLAMPY: '{{.FOLDERLAMPY | default "lampy"}}'
  DOCKERCOMPOSEFILE: '{{.DOCKERCOMPOSEFILE | default "docker-compose-lampy.yml"}}'

tasks:
  default:
    desc: "Affiche l'aide et les tâches disponibles"
    silent: true
    cmds:
    - echo "🛠️  Collection de Taskfiles pour le développement"
    - echo ""
    - echo "Tâches globales disponibles :"
    - task --list
    - echo ""

  lint:all:
    desc: "Exécute tous les linters disponibles"
    cmds:
    - npm run lint:markdown

  info:
    desc: "Affiche les informations du projet avec les variables d'environnement"
    silent: true
    cmds:
    - |
      export PROJECT_VERSION=$(jq -r .version package.json)
      echo "🛠️  {{.PROJECT_NAME}} v$PROJECT_VERSION - Collection de Taskfiles"
      echo "Environnement: {{.ENVIRONMENT}}"

  help:
    desc: "Affiche l'aide détaillée"
    aliases: [ h ]
    silent: true
    cmds:
    - task: default

  react:getpull-image:
    desc: "Télécharge les images Docker définies dans le docker-compose.yml"
    silent: true
    cmds:
    - task: docker:images:pull
      vars:
        COMPOSE_FILE: "{{.DOCKERCOMPOSEFILE}}"

  react:deploy:
    desc: "Déploie les stacks Docker définies dans les fichiers docker-compose"
    silent: true
    cmds:
    - task: docker:stack:deploy
      vars:
        COMPOSE_FILE: "{{.DOCKERCOMPOSEFILE}}"
        STACK_NAME: "{{.STACK_NAME}}"

  react:waiting:
    desc: "Attend que les services soient opérationnels"
    silent: true
    cmds:
    - task: docker:stack:check:containers:ready
      vars:
        CONTAINERS: "www"
        STACK_NAME: "{{.STACK_NAME}}"

  react:ls:
    desc: "Liste les stacks et services Docker"
    silent: true
    cmds:
    - task: docker:stack:services
      vars:
        STACK_NAME: "{{.STACK_NAME}}"

  create:apps:
    desc: "Crée une nouvelle application react dans le dossier apps"
    silent: true
    cmds:
    - CI=true npx create-react-app apps --template typescript

  react:exec:
    desc: "Exécute une commande dans un conteneur en cours d'exécution"
    silent: true
    cmds:
    - task: react:getpull-image
    - task: create:apps
    - task: react:deploy
    - task: react:waiting
    - task: react:ls

  react:bash:
    desc: "Ouvre un shell bash dans le conteneur www"
    silent: true
    cmds:
    - task: docker:stack:shell
      vars:
        STACK_NAME: "react"
        SERVICE_NAME: "www"
